[package]
name = "anti_debug"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
windows = { version = "0.58.0", features = ["Win32_System_Diagnostics_Debug", "Win32_System_Memory"] }
